# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: Foo.proto

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='Foo.proto',
  package='',
  syntax='proto2',
  serialized_pb=b'\n\tFoo.proto'
)
_sym_db.RegisterFileDescriptor(DESCRIPTOR)





# @@protoc_insertion_point(module_scope)
