# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: iptunnels.proto

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import jvision_top_pb2 as jvision__top__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='iptunnels.proto',
  package='',
  syntax='proto2',
  serialized_pb=b'\n\x0fiptunnels.proto\x1a\x11jvision_top.proto\"E\n\rIpTunnelStats\x12\x34\n\x16iptunnel_stats_records\x18\x01 \x03(\x0b\x32\x14.IpTunnelStatsRecord\"\xa5\x01\n\x13IpTunnelStatsRecord\x12\x0c\n\x04name\x18\x01 \x02(\t\x12\x12\n\nrx_packets\x18\x02 \x01(\x04\x12\x10\n\x08rx_bytes\x18\x03 \x01(\x04\x12\x12\n\ntx_packets\x18\x04 \x01(\x04\x12\x10\n\x08tx_bytes\x18\x05 \x01(\x04\x12\x1a\n\x12rpf_failed_packets\x18\x06 \x01(\x04\x12\x18\n\x10rpf_failed_bytes\x18\x07 \x01(\x04:N\n\x1djnpr_iptunnels_statistics_ext\x12\x17.JuniperNetworksSensors\x18\x0e \x01(\x0b\x32\x0e.IpTunnelStats'
  ,
  dependencies=[jvision__top__pb2.DESCRIPTOR,])
_sym_db.RegisterFileDescriptor(DESCRIPTOR)


JNPR_IPTUNNELS_STATISTICS_EXT_FIELD_NUMBER = 14
jnpr_iptunnels_statistics_ext = _descriptor.FieldDescriptor(
  name='jnpr_iptunnels_statistics_ext', full_name='jnpr_iptunnels_statistics_ext', index=0,
  number=14, type=11, cpp_type=10, label=1,
  has_default_value=False, default_value=None,
  message_type=None, enum_type=None, containing_type=None,
  is_extension=True, extension_scope=None,
  options=None)


_IPTUNNELSTATS = _descriptor.Descriptor(
  name='IpTunnelStats',
  full_name='IpTunnelStats',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='iptunnel_stats_records', full_name='IpTunnelStats.iptunnel_stats_records', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=38,
  serialized_end=107,
)


_IPTUNNELSTATSRECORD = _descriptor.Descriptor(
  name='IpTunnelStatsRecord',
  full_name='IpTunnelStatsRecord',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='name', full_name='IpTunnelStatsRecord.name', index=0,
      number=1, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='rx_packets', full_name='IpTunnelStatsRecord.rx_packets', index=1,
      number=2, type=4, cpp_type=4, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='rx_bytes', full_name='IpTunnelStatsRecord.rx_bytes', index=2,
      number=3, type=4, cpp_type=4, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='tx_packets', full_name='IpTunnelStatsRecord.tx_packets', index=3,
      number=4, type=4, cpp_type=4, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='tx_bytes', full_name='IpTunnelStatsRecord.tx_bytes', index=4,
      number=5, type=4, cpp_type=4, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='rpf_failed_packets', full_name='IpTunnelStatsRecord.rpf_failed_packets', index=5,
      number=6, type=4, cpp_type=4, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='rpf_failed_bytes', full_name='IpTunnelStatsRecord.rpf_failed_bytes', index=6,
      number=7, type=4, cpp_type=4, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=110,
  serialized_end=275,
)

_IPTUNNELSTATS.fields_by_name['iptunnel_stats_records'].message_type = _IPTUNNELSTATSRECORD
DESCRIPTOR.message_types_by_name['IpTunnelStats'] = _IPTUNNELSTATS
DESCRIPTOR.message_types_by_name['IpTunnelStatsRecord'] = _IPTUNNELSTATSRECORD
DESCRIPTOR.extensions_by_name['jnpr_iptunnels_statistics_ext'] = jnpr_iptunnels_statistics_ext

IpTunnelStats = _reflection.GeneratedProtocolMessageType('IpTunnelStats', (_message.Message,), dict(
  DESCRIPTOR = _IPTUNNELSTATS,
  __module__ = 'iptunnels_pb2'
  # @@protoc_insertion_point(class_scope:IpTunnelStats)
  ))
_sym_db.RegisterMessage(IpTunnelStats)

IpTunnelStatsRecord = _reflection.GeneratedProtocolMessageType('IpTunnelStatsRecord', (_message.Message,), dict(
  DESCRIPTOR = _IPTUNNELSTATSRECORD,
  __module__ = 'iptunnels_pb2'
  # @@protoc_insertion_point(class_scope:IpTunnelStatsRecord)
  ))
_sym_db.RegisterMessage(IpTunnelStatsRecord)

jnpr_iptunnels_statistics_ext.message_type = _IPTUNNELSTATS
jvision__top__pb2.JuniperNetworksSensors.RegisterExtension(jnpr_iptunnels_statistics_ext)

# @@protoc_insertion_point(module_scope)
