// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: port.proto

#ifndef PROTOBUF_port_2eproto__INCLUDED
#define PROTOBUF_port_2eproto__INCLUDED

#include <string>

#include <google/protobuf/stubs/common.h>

#if GOOGLE_PROTOBUF_VERSION < 3000000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please update
#error your headers.
#endif
#if 3000000 < GOOGLE_PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/arena.h>
#include <google/protobuf/arenastring.h>
#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/metadata.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>
#include <google/protobuf/extension_set.h>
#include <google/protobuf/unknown_field_set.h>
#include "telemetry_top.pb.h"
// @@protoc_insertion_point(includes)

// Internal implementation detail -- do not call these.
void protobuf_AddDesc_port_2eproto();
void protobuf_AssignDesc_port_2eproto();
void protobuf_ShutdownFile_port_2eproto();

class GPort;
class IngressInterfaceErrors;
class InterfaceInfos;
class InterfaceStats;
class QueueStats;

// ===================================================================

class GPort : public ::google::protobuf::Message {
 public:
  GPort();
  virtual ~GPort();

  GPort(const GPort& from);

  inline GPort& operator=(const GPort& from) {
    CopyFrom(from);
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _internal_metadata_.unknown_fields();
  }

  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return _internal_metadata_.mutable_unknown_fields();
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const GPort& default_instance();

  void Swap(GPort* other);

  // implements Message ----------------------------------------------

  inline GPort* New() const { return New(NULL); }

  GPort* New(::google::protobuf::Arena* arena) const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const GPort& from);
  void MergeFrom(const GPort& from);
  void Clear();
  bool IsInitialized() const;

  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const;
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  void InternalSwap(GPort* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return _internal_metadata_.arena();
  }
  inline void* MaybeArenaPtr() const {
    return _internal_metadata_.raw_arena_ptr();
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // repeated .InterfaceInfos interface_stats = 1;
  int interface_stats_size() const;
  void clear_interface_stats();
  static const int kInterfaceStatsFieldNumber = 1;
  const ::InterfaceInfos& interface_stats(int index) const;
  ::InterfaceInfos* mutable_interface_stats(int index);
  ::InterfaceInfos* add_interface_stats();
  ::google::protobuf::RepeatedPtrField< ::InterfaceInfos >*
      mutable_interface_stats();
  const ::google::protobuf::RepeatedPtrField< ::InterfaceInfos >&
      interface_stats() const;

  // @@protoc_insertion_point(class_scope:GPort)
 private:

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  ::google::protobuf::uint32 _has_bits_[1];
  mutable int _cached_size_;
  ::google::protobuf::RepeatedPtrField< ::InterfaceInfos > interface_stats_;
  friend void  protobuf_AddDesc_port_2eproto();
  friend void protobuf_AssignDesc_port_2eproto();
  friend void protobuf_ShutdownFile_port_2eproto();

  void InitAsDefaultInstance();
  static GPort* default_instance_;
};
// -------------------------------------------------------------------

class InterfaceInfos : public ::google::protobuf::Message {
 public:
  InterfaceInfos();
  virtual ~InterfaceInfos();

  InterfaceInfos(const InterfaceInfos& from);

  inline InterfaceInfos& operator=(const InterfaceInfos& from) {
    CopyFrom(from);
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _internal_metadata_.unknown_fields();
  }

  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return _internal_metadata_.mutable_unknown_fields();
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const InterfaceInfos& default_instance();

  void Swap(InterfaceInfos* other);

  // implements Message ----------------------------------------------

  inline InterfaceInfos* New() const { return New(NULL); }

  InterfaceInfos* New(::google::protobuf::Arena* arena) const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const InterfaceInfos& from);
  void MergeFrom(const InterfaceInfos& from);
  void Clear();
  bool IsInitialized() const;

  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const;
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  void InternalSwap(InterfaceInfos* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return _internal_metadata_.arena();
  }
  inline void* MaybeArenaPtr() const {
    return _internal_metadata_.raw_arena_ptr();
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // required string if_name = 1;
  bool has_if_name() const;
  void clear_if_name();
  static const int kIfNameFieldNumber = 1;
  const ::std::string& if_name() const;
  void set_if_name(const ::std::string& value);
  void set_if_name(const char* value);
  void set_if_name(const char* value, size_t size);
  ::std::string* mutable_if_name();
  ::std::string* release_if_name();
  void set_allocated_if_name(::std::string* if_name);

  // required uint64 init_time = 2;
  bool has_init_time() const;
  void clear_init_time();
  static const int kInitTimeFieldNumber = 2;
  ::google::protobuf::uint64 init_time() const;
  void set_init_time(::google::protobuf::uint64 value);

  // optional uint32 snmp_if_index = 3;
  bool has_snmp_if_index() const;
  void clear_snmp_if_index();
  static const int kSnmpIfIndexFieldNumber = 3;
  ::google::protobuf::uint32 snmp_if_index() const;
  void set_snmp_if_index(::google::protobuf::uint32 value);

  // optional string parent_ae_name = 4;
  bool has_parent_ae_name() const;
  void clear_parent_ae_name();
  static const int kParentAeNameFieldNumber = 4;
  const ::std::string& parent_ae_name() const;
  void set_parent_ae_name(const ::std::string& value);
  void set_parent_ae_name(const char* value);
  void set_parent_ae_name(const char* value, size_t size);
  ::std::string* mutable_parent_ae_name();
  ::std::string* release_parent_ae_name();
  void set_allocated_parent_ae_name(::std::string* parent_ae_name);

  // repeated .QueueStats egress_queue_info = 5;
  int egress_queue_info_size() const;
  void clear_egress_queue_info();
  static const int kEgressQueueInfoFieldNumber = 5;
  const ::QueueStats& egress_queue_info(int index) const;
  ::QueueStats* mutable_egress_queue_info(int index);
  ::QueueStats* add_egress_queue_info();
  ::google::protobuf::RepeatedPtrField< ::QueueStats >*
      mutable_egress_queue_info();
  const ::google::protobuf::RepeatedPtrField< ::QueueStats >&
      egress_queue_info() const;

  // repeated .QueueStats ingress_queue_info = 6;
  int ingress_queue_info_size() const;
  void clear_ingress_queue_info();
  static const int kIngressQueueInfoFieldNumber = 6;
  const ::QueueStats& ingress_queue_info(int index) const;
  ::QueueStats* mutable_ingress_queue_info(int index);
  ::QueueStats* add_ingress_queue_info();
  ::google::protobuf::RepeatedPtrField< ::QueueStats >*
      mutable_ingress_queue_info();
  const ::google::protobuf::RepeatedPtrField< ::QueueStats >&
      ingress_queue_info() const;

  // optional .InterfaceStats ingress_stats = 7;
  bool has_ingress_stats() const;
  void clear_ingress_stats();
  static const int kIngressStatsFieldNumber = 7;
  const ::InterfaceStats& ingress_stats() const;
  ::InterfaceStats* mutable_ingress_stats();
  ::InterfaceStats* release_ingress_stats();
  void set_allocated_ingress_stats(::InterfaceStats* ingress_stats);

  // optional .InterfaceStats egress_stats = 8;
  bool has_egress_stats() const;
  void clear_egress_stats();
  static const int kEgressStatsFieldNumber = 8;
  const ::InterfaceStats& egress_stats() const;
  ::InterfaceStats* mutable_egress_stats();
  ::InterfaceStats* release_egress_stats();
  void set_allocated_egress_stats(::InterfaceStats* egress_stats);

  // optional .IngressInterfaceErrors ingress_errors = 9;
  bool has_ingress_errors() const;
  void clear_ingress_errors();
  static const int kIngressErrorsFieldNumber = 9;
  const ::IngressInterfaceErrors& ingress_errors() const;
  ::IngressInterfaceErrors* mutable_ingress_errors();
  ::IngressInterfaceErrors* release_ingress_errors();
  void set_allocated_ingress_errors(::IngressInterfaceErrors* ingress_errors);

  // optional string if_administration_status = 10;
  bool has_if_administration_status() const;
  void clear_if_administration_status();
  static const int kIfAdministrationStatusFieldNumber = 10;
  const ::std::string& if_administration_status() const;
  void set_if_administration_status(const ::std::string& value);
  void set_if_administration_status(const char* value);
  void set_if_administration_status(const char* value, size_t size);
  ::std::string* mutable_if_administration_status();
  ::std::string* release_if_administration_status();
  void set_allocated_if_administration_status(::std::string* if_administration_status);

  // optional string if_operational_status = 11;
  bool has_if_operational_status() const;
  void clear_if_operational_status();
  static const int kIfOperationalStatusFieldNumber = 11;
  const ::std::string& if_operational_status() const;
  void set_if_operational_status(const ::std::string& value);
  void set_if_operational_status(const char* value);
  void set_if_operational_status(const char* value, size_t size);
  ::std::string* mutable_if_operational_status();
  ::std::string* release_if_operational_status();
  void set_allocated_if_operational_status(::std::string* if_operational_status);

  // optional string if_description = 12;
  bool has_if_description() const;
  void clear_if_description();
  static const int kIfDescriptionFieldNumber = 12;
  const ::std::string& if_description() const;
  void set_if_description(const ::std::string& value);
  void set_if_description(const char* value);
  void set_if_description(const char* value, size_t size);
  ::std::string* mutable_if_description();
  ::std::string* release_if_description();
  void set_allocated_if_description(::std::string* if_description);

  // optional uint64 if_transitions = 13;
  bool has_if_transitions() const;
  void clear_if_transitions();
  static const int kIfTransitionsFieldNumber = 13;
  ::google::protobuf::uint64 if_transitions() const;
  void set_if_transitions(::google::protobuf::uint64 value);

  // optional uint32 ifLastChange = 14;
  bool has_iflastchange() const;
  void clear_iflastchange();
  static const int kIfLastChangeFieldNumber = 14;
  ::google::protobuf::uint32 iflastchange() const;
  void set_iflastchange(::google::protobuf::uint32 value);

  // optional uint32 ifHighSpeed = 15;
  bool has_ifhighspeed() const;
  void clear_ifhighspeed();
  static const int kIfHighSpeedFieldNumber = 15;
  ::google::protobuf::uint32 ifhighspeed() const;
  void set_ifhighspeed(::google::protobuf::uint32 value);

  // @@protoc_insertion_point(class_scope:InterfaceInfos)
 private:
  inline void set_has_if_name();
  inline void clear_has_if_name();
  inline void set_has_init_time();
  inline void clear_has_init_time();
  inline void set_has_snmp_if_index();
  inline void clear_has_snmp_if_index();
  inline void set_has_parent_ae_name();
  inline void clear_has_parent_ae_name();
  inline void set_has_ingress_stats();
  inline void clear_has_ingress_stats();
  inline void set_has_egress_stats();
  inline void clear_has_egress_stats();
  inline void set_has_ingress_errors();
  inline void clear_has_ingress_errors();
  inline void set_has_if_administration_status();
  inline void clear_has_if_administration_status();
  inline void set_has_if_operational_status();
  inline void clear_has_if_operational_status();
  inline void set_has_if_description();
  inline void clear_has_if_description();
  inline void set_has_if_transitions();
  inline void clear_has_if_transitions();
  inline void set_has_iflastchange();
  inline void clear_has_iflastchange();
  inline void set_has_ifhighspeed();
  inline void clear_has_ifhighspeed();

  // helper for ByteSize()
  int RequiredFieldsByteSizeFallback() const;

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  ::google::protobuf::uint32 _has_bits_[1];
  mutable int _cached_size_;
  ::google::protobuf::internal::ArenaStringPtr if_name_;
  ::google::protobuf::uint64 init_time_;
  ::google::protobuf::internal::ArenaStringPtr parent_ae_name_;
  ::google::protobuf::RepeatedPtrField< ::QueueStats > egress_queue_info_;
  ::google::protobuf::RepeatedPtrField< ::QueueStats > ingress_queue_info_;
  ::InterfaceStats* ingress_stats_;
  ::InterfaceStats* egress_stats_;
  ::google::protobuf::uint32 snmp_if_index_;
  ::google::protobuf::uint32 iflastchange_;
  ::IngressInterfaceErrors* ingress_errors_;
  ::google::protobuf::internal::ArenaStringPtr if_administration_status_;
  ::google::protobuf::internal::ArenaStringPtr if_operational_status_;
  ::google::protobuf::internal::ArenaStringPtr if_description_;
  ::google::protobuf::uint64 if_transitions_;
  ::google::protobuf::uint32 ifhighspeed_;
  friend void  protobuf_AddDesc_port_2eproto();
  friend void protobuf_AssignDesc_port_2eproto();
  friend void protobuf_ShutdownFile_port_2eproto();

  void InitAsDefaultInstance();
  static InterfaceInfos* default_instance_;
};
// -------------------------------------------------------------------

class InterfaceStats : public ::google::protobuf::Message {
 public:
  InterfaceStats();
  virtual ~InterfaceStats();

  InterfaceStats(const InterfaceStats& from);

  inline InterfaceStats& operator=(const InterfaceStats& from) {
    CopyFrom(from);
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _internal_metadata_.unknown_fields();
  }

  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return _internal_metadata_.mutable_unknown_fields();
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const InterfaceStats& default_instance();

  void Swap(InterfaceStats* other);

  // implements Message ----------------------------------------------

  inline InterfaceStats* New() const { return New(NULL); }

  InterfaceStats* New(::google::protobuf::Arena* arena) const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const InterfaceStats& from);
  void MergeFrom(const InterfaceStats& from);
  void Clear();
  bool IsInitialized() const;

  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const;
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  void InternalSwap(InterfaceStats* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return _internal_metadata_.arena();
  }
  inline void* MaybeArenaPtr() const {
    return _internal_metadata_.raw_arena_ptr();
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // required uint64 if_pkts = 1;
  bool has_if_pkts() const;
  void clear_if_pkts();
  static const int kIfPktsFieldNumber = 1;
  ::google::protobuf::uint64 if_pkts() const;
  void set_if_pkts(::google::protobuf::uint64 value);

  // required uint64 if_octets = 2;
  bool has_if_octets() const;
  void clear_if_octets();
  static const int kIfOctetsFieldNumber = 2;
  ::google::protobuf::uint64 if_octets() const;
  void set_if_octets(::google::protobuf::uint64 value);

  // required uint64 if_1sec_pkts = 3;
  bool has_if_1sec_pkts() const;
  void clear_if_1sec_pkts();
  static const int kIf1SecPktsFieldNumber = 3;
  ::google::protobuf::uint64 if_1sec_pkts() const;
  void set_if_1sec_pkts(::google::protobuf::uint64 value);

  // required uint64 if_1sec_octets = 4;
  bool has_if_1sec_octets() const;
  void clear_if_1sec_octets();
  static const int kIf1SecOctetsFieldNumber = 4;
  ::google::protobuf::uint64 if_1sec_octets() const;
  void set_if_1sec_octets(::google::protobuf::uint64 value);

  // required uint64 if_uc_pkts = 5;
  bool has_if_uc_pkts() const;
  void clear_if_uc_pkts();
  static const int kIfUcPktsFieldNumber = 5;
  ::google::protobuf::uint64 if_uc_pkts() const;
  void set_if_uc_pkts(::google::protobuf::uint64 value);

  // required uint64 if_mc_pkts = 6;
  bool has_if_mc_pkts() const;
  void clear_if_mc_pkts();
  static const int kIfMcPktsFieldNumber = 6;
  ::google::protobuf::uint64 if_mc_pkts() const;
  void set_if_mc_pkts(::google::protobuf::uint64 value);

  // required uint64 if_bc_pkts = 7;
  bool has_if_bc_pkts() const;
  void clear_if_bc_pkts();
  static const int kIfBcPktsFieldNumber = 7;
  ::google::protobuf::uint64 if_bc_pkts() const;
  void set_if_bc_pkts(::google::protobuf::uint64 value);

  // optional uint64 if_error = 8;
  bool has_if_error() const;
  void clear_if_error();
  static const int kIfErrorFieldNumber = 8;
  ::google::protobuf::uint64 if_error() const;
  void set_if_error(::google::protobuf::uint64 value);

  // optional uint64 if_pause_pkts = 9;
  bool has_if_pause_pkts() const;
  void clear_if_pause_pkts();
  static const int kIfPausePktsFieldNumber = 9;
  ::google::protobuf::uint64 if_pause_pkts() const;
  void set_if_pause_pkts(::google::protobuf::uint64 value);

  // @@protoc_insertion_point(class_scope:InterfaceStats)
 private:
  inline void set_has_if_pkts();
  inline void clear_has_if_pkts();
  inline void set_has_if_octets();
  inline void clear_has_if_octets();
  inline void set_has_if_1sec_pkts();
  inline void clear_has_if_1sec_pkts();
  inline void set_has_if_1sec_octets();
  inline void clear_has_if_1sec_octets();
  inline void set_has_if_uc_pkts();
  inline void clear_has_if_uc_pkts();
  inline void set_has_if_mc_pkts();
  inline void clear_has_if_mc_pkts();
  inline void set_has_if_bc_pkts();
  inline void clear_has_if_bc_pkts();
  inline void set_has_if_error();
  inline void clear_has_if_error();
  inline void set_has_if_pause_pkts();
  inline void clear_has_if_pause_pkts();

  // helper for ByteSize()
  int RequiredFieldsByteSizeFallback() const;

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  ::google::protobuf::uint32 _has_bits_[1];
  mutable int _cached_size_;
  ::google::protobuf::uint64 if_pkts_;
  ::google::protobuf::uint64 if_octets_;
  ::google::protobuf::uint64 if_1sec_pkts_;
  ::google::protobuf::uint64 if_1sec_octets_;
  ::google::protobuf::uint64 if_uc_pkts_;
  ::google::protobuf::uint64 if_mc_pkts_;
  ::google::protobuf::uint64 if_bc_pkts_;
  ::google::protobuf::uint64 if_error_;
  ::google::protobuf::uint64 if_pause_pkts_;
  friend void  protobuf_AddDesc_port_2eproto();
  friend void protobuf_AssignDesc_port_2eproto();
  friend void protobuf_ShutdownFile_port_2eproto();

  void InitAsDefaultInstance();
  static InterfaceStats* default_instance_;
};
// -------------------------------------------------------------------

class IngressInterfaceErrors : public ::google::protobuf::Message {
 public:
  IngressInterfaceErrors();
  virtual ~IngressInterfaceErrors();

  IngressInterfaceErrors(const IngressInterfaceErrors& from);

  inline IngressInterfaceErrors& operator=(const IngressInterfaceErrors& from) {
    CopyFrom(from);
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _internal_metadata_.unknown_fields();
  }

  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return _internal_metadata_.mutable_unknown_fields();
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const IngressInterfaceErrors& default_instance();

  void Swap(IngressInterfaceErrors* other);

  // implements Message ----------------------------------------------

  inline IngressInterfaceErrors* New() const { return New(NULL); }

  IngressInterfaceErrors* New(::google::protobuf::Arena* arena) const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const IngressInterfaceErrors& from);
  void MergeFrom(const IngressInterfaceErrors& from);
  void Clear();
  bool IsInitialized() const;

  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const;
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  void InternalSwap(IngressInterfaceErrors* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return _internal_metadata_.arena();
  }
  inline void* MaybeArenaPtr() const {
    return _internal_metadata_.raw_arena_ptr();
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // optional uint64 if_in_errors = 1;
  bool has_if_in_errors() const;
  void clear_if_in_errors();
  static const int kIfInErrorsFieldNumber = 1;
  ::google::protobuf::uint64 if_in_errors() const;
  void set_if_in_errors(::google::protobuf::uint64 value);

  // optional uint64 if_in_qdrops = 2;
  bool has_if_in_qdrops() const;
  void clear_if_in_qdrops();
  static const int kIfInQdropsFieldNumber = 2;
  ::google::protobuf::uint64 if_in_qdrops() const;
  void set_if_in_qdrops(::google::protobuf::uint64 value);

  // optional uint64 if_in_frame_errors = 3;
  bool has_if_in_frame_errors() const;
  void clear_if_in_frame_errors();
  static const int kIfInFrameErrorsFieldNumber = 3;
  ::google::protobuf::uint64 if_in_frame_errors() const;
  void set_if_in_frame_errors(::google::protobuf::uint64 value);

  // optional uint64 if_in_discards = 4;
  bool has_if_in_discards() const;
  void clear_if_in_discards();
  static const int kIfInDiscardsFieldNumber = 4;
  ::google::protobuf::uint64 if_in_discards() const;
  void set_if_in_discards(::google::protobuf::uint64 value);

  // optional uint64 if_in_runts = 5;
  bool has_if_in_runts() const;
  void clear_if_in_runts();
  static const int kIfInRuntsFieldNumber = 5;
  ::google::protobuf::uint64 if_in_runts() const;
  void set_if_in_runts(::google::protobuf::uint64 value);

  // optional uint64 if_in_l3_incompletes = 6;
  bool has_if_in_l3_incompletes() const;
  void clear_if_in_l3_incompletes();
  static const int kIfInL3IncompletesFieldNumber = 6;
  ::google::protobuf::uint64 if_in_l3_incompletes() const;
  void set_if_in_l3_incompletes(::google::protobuf::uint64 value);

  // optional uint64 if_in_l2chan_errors = 7;
  bool has_if_in_l2chan_errors() const;
  void clear_if_in_l2chan_errors();
  static const int kIfInL2ChanErrorsFieldNumber = 7;
  ::google::protobuf::uint64 if_in_l2chan_errors() const;
  void set_if_in_l2chan_errors(::google::protobuf::uint64 value);

  // optional uint64 if_in_l2_mismatch_timeouts = 8;
  bool has_if_in_l2_mismatch_timeouts() const;
  void clear_if_in_l2_mismatch_timeouts();
  static const int kIfInL2MismatchTimeoutsFieldNumber = 8;
  ::google::protobuf::uint64 if_in_l2_mismatch_timeouts() const;
  void set_if_in_l2_mismatch_timeouts(::google::protobuf::uint64 value);

  // optional uint64 if_in_fifo_errors = 9;
  bool has_if_in_fifo_errors() const;
  void clear_if_in_fifo_errors();
  static const int kIfInFifoErrorsFieldNumber = 9;
  ::google::protobuf::uint64 if_in_fifo_errors() const;
  void set_if_in_fifo_errors(::google::protobuf::uint64 value);

  // optional uint64 if_in_resource_errors = 10;
  bool has_if_in_resource_errors() const;
  void clear_if_in_resource_errors();
  static const int kIfInResourceErrorsFieldNumber = 10;
  ::google::protobuf::uint64 if_in_resource_errors() const;
  void set_if_in_resource_errors(::google::protobuf::uint64 value);

  // @@protoc_insertion_point(class_scope:IngressInterfaceErrors)
 private:
  inline void set_has_if_in_errors();
  inline void clear_has_if_in_errors();
  inline void set_has_if_in_qdrops();
  inline void clear_has_if_in_qdrops();
  inline void set_has_if_in_frame_errors();
  inline void clear_has_if_in_frame_errors();
  inline void set_has_if_in_discards();
  inline void clear_has_if_in_discards();
  inline void set_has_if_in_runts();
  inline void clear_has_if_in_runts();
  inline void set_has_if_in_l3_incompletes();
  inline void clear_has_if_in_l3_incompletes();
  inline void set_has_if_in_l2chan_errors();
  inline void clear_has_if_in_l2chan_errors();
  inline void set_has_if_in_l2_mismatch_timeouts();
  inline void clear_has_if_in_l2_mismatch_timeouts();
  inline void set_has_if_in_fifo_errors();
  inline void clear_has_if_in_fifo_errors();
  inline void set_has_if_in_resource_errors();
  inline void clear_has_if_in_resource_errors();

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  ::google::protobuf::uint32 _has_bits_[1];
  mutable int _cached_size_;
  ::google::protobuf::uint64 if_in_errors_;
  ::google::protobuf::uint64 if_in_qdrops_;
  ::google::protobuf::uint64 if_in_frame_errors_;
  ::google::protobuf::uint64 if_in_discards_;
  ::google::protobuf::uint64 if_in_runts_;
  ::google::protobuf::uint64 if_in_l3_incompletes_;
  ::google::protobuf::uint64 if_in_l2chan_errors_;
  ::google::protobuf::uint64 if_in_l2_mismatch_timeouts_;
  ::google::protobuf::uint64 if_in_fifo_errors_;
  ::google::protobuf::uint64 if_in_resource_errors_;
  friend void  protobuf_AddDesc_port_2eproto();
  friend void protobuf_AssignDesc_port_2eproto();
  friend void protobuf_ShutdownFile_port_2eproto();

  void InitAsDefaultInstance();
  static IngressInterfaceErrors* default_instance_;
};
// -------------------------------------------------------------------

class QueueStats : public ::google::protobuf::Message {
 public:
  QueueStats();
  virtual ~QueueStats();

  QueueStats(const QueueStats& from);

  inline QueueStats& operator=(const QueueStats& from) {
    CopyFrom(from);
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _internal_metadata_.unknown_fields();
  }

  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return _internal_metadata_.mutable_unknown_fields();
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const QueueStats& default_instance();

  void Swap(QueueStats* other);

  // implements Message ----------------------------------------------

  inline QueueStats* New() const { return New(NULL); }

  QueueStats* New(::google::protobuf::Arena* arena) const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const QueueStats& from);
  void MergeFrom(const QueueStats& from);
  void Clear();
  bool IsInitialized() const;

  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const;
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  void InternalSwap(QueueStats* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return _internal_metadata_.arena();
  }
  inline void* MaybeArenaPtr() const {
    return _internal_metadata_.raw_arena_ptr();
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // optional uint32 queue_number = 1;
  bool has_queue_number() const;
  void clear_queue_number();
  static const int kQueueNumberFieldNumber = 1;
  ::google::protobuf::uint32 queue_number() const;
  void set_queue_number(::google::protobuf::uint32 value);

  // optional uint64 packets = 2;
  bool has_packets() const;
  void clear_packets();
  static const int kPacketsFieldNumber = 2;
  ::google::protobuf::uint64 packets() const;
  void set_packets(::google::protobuf::uint64 value);

  // optional uint64 bytes = 3;
  bool has_bytes() const;
  void clear_bytes();
  static const int kBytesFieldNumber = 3;
  ::google::protobuf::uint64 bytes() const;
  void set_bytes(::google::protobuf::uint64 value);

  // optional uint64 tail_drop_packets = 4;
  bool has_tail_drop_packets() const;
  void clear_tail_drop_packets();
  static const int kTailDropPacketsFieldNumber = 4;
  ::google::protobuf::uint64 tail_drop_packets() const;
  void set_tail_drop_packets(::google::protobuf::uint64 value);

  // optional uint64 rl_drop_packets = 5;
  bool has_rl_drop_packets() const;
  void clear_rl_drop_packets();
  static const int kRlDropPacketsFieldNumber = 5;
  ::google::protobuf::uint64 rl_drop_packets() const;
  void set_rl_drop_packets(::google::protobuf::uint64 value);

  // optional uint64 rl_drop_bytes = 6;
  bool has_rl_drop_bytes() const;
  void clear_rl_drop_bytes();
  static const int kRlDropBytesFieldNumber = 6;
  ::google::protobuf::uint64 rl_drop_bytes() const;
  void set_rl_drop_bytes(::google::protobuf::uint64 value);

  // optional uint64 red_drop_packets = 7;
  bool has_red_drop_packets() const;
  void clear_red_drop_packets();
  static const int kRedDropPacketsFieldNumber = 7;
  ::google::protobuf::uint64 red_drop_packets() const;
  void set_red_drop_packets(::google::protobuf::uint64 value);

  // optional uint64 red_drop_bytes = 8;
  bool has_red_drop_bytes() const;
  void clear_red_drop_bytes();
  static const int kRedDropBytesFieldNumber = 8;
  ::google::protobuf::uint64 red_drop_bytes() const;
  void set_red_drop_bytes(::google::protobuf::uint64 value);

  // optional uint64 avg_buffer_occupancy = 9;
  bool has_avg_buffer_occupancy() const;
  void clear_avg_buffer_occupancy();
  static const int kAvgBufferOccupancyFieldNumber = 9;
  ::google::protobuf::uint64 avg_buffer_occupancy() const;
  void set_avg_buffer_occupancy(::google::protobuf::uint64 value);

  // optional uint64 cur_buffer_occupancy = 10;
  bool has_cur_buffer_occupancy() const;
  void clear_cur_buffer_occupancy();
  static const int kCurBufferOccupancyFieldNumber = 10;
  ::google::protobuf::uint64 cur_buffer_occupancy() const;
  void set_cur_buffer_occupancy(::google::protobuf::uint64 value);

  // optional uint64 peak_buffer_occupancy = 11;
  bool has_peak_buffer_occupancy() const;
  void clear_peak_buffer_occupancy();
  static const int kPeakBufferOccupancyFieldNumber = 11;
  ::google::protobuf::uint64 peak_buffer_occupancy() const;
  void set_peak_buffer_occupancy(::google::protobuf::uint64 value);

  // optional uint64 allocated_buffer_size = 12;
  bool has_allocated_buffer_size() const;
  void clear_allocated_buffer_size();
  static const int kAllocatedBufferSizeFieldNumber = 12;
  ::google::protobuf::uint64 allocated_buffer_size() const;
  void set_allocated_buffer_size(::google::protobuf::uint64 value);

  // @@protoc_insertion_point(class_scope:QueueStats)
 private:
  inline void set_has_queue_number();
  inline void clear_has_queue_number();
  inline void set_has_packets();
  inline void clear_has_packets();
  inline void set_has_bytes();
  inline void clear_has_bytes();
  inline void set_has_tail_drop_packets();
  inline void clear_has_tail_drop_packets();
  inline void set_has_rl_drop_packets();
  inline void clear_has_rl_drop_packets();
  inline void set_has_rl_drop_bytes();
  inline void clear_has_rl_drop_bytes();
  inline void set_has_red_drop_packets();
  inline void clear_has_red_drop_packets();
  inline void set_has_red_drop_bytes();
  inline void clear_has_red_drop_bytes();
  inline void set_has_avg_buffer_occupancy();
  inline void clear_has_avg_buffer_occupancy();
  inline void set_has_cur_buffer_occupancy();
  inline void clear_has_cur_buffer_occupancy();
  inline void set_has_peak_buffer_occupancy();
  inline void clear_has_peak_buffer_occupancy();
  inline void set_has_allocated_buffer_size();
  inline void clear_has_allocated_buffer_size();

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  ::google::protobuf::uint32 _has_bits_[1];
  mutable int _cached_size_;
  ::google::protobuf::uint64 packets_;
  ::google::protobuf::uint64 bytes_;
  ::google::protobuf::uint64 tail_drop_packets_;
  ::google::protobuf::uint64 rl_drop_packets_;
  ::google::protobuf::uint64 rl_drop_bytes_;
  ::google::protobuf::uint64 red_drop_packets_;
  ::google::protobuf::uint64 red_drop_bytes_;
  ::google::protobuf::uint64 avg_buffer_occupancy_;
  ::google::protobuf::uint64 cur_buffer_occupancy_;
  ::google::protobuf::uint64 peak_buffer_occupancy_;
  ::google::protobuf::uint64 allocated_buffer_size_;
  ::google::protobuf::uint32 queue_number_;
  friend void  protobuf_AddDesc_port_2eproto();
  friend void protobuf_AssignDesc_port_2eproto();
  friend void protobuf_ShutdownFile_port_2eproto();

  void InitAsDefaultInstance();
  static QueueStats* default_instance_;
};
// ===================================================================

static const int kJnprInterfaceExtFieldNumber = 3;
extern ::google::protobuf::internal::ExtensionIdentifier< ::JuniperNetworksSensors,
    ::google::protobuf::internal::MessageTypeTraits< ::GPort >, 11, false >
  jnpr_interface_ext;

// ===================================================================

#if !PROTOBUF_INLINE_NOT_IN_HEADERS
// GPort

// repeated .InterfaceInfos interface_stats = 1;
inline int GPort::interface_stats_size() const {
  return interface_stats_.size();
}
inline void GPort::clear_interface_stats() {
  interface_stats_.Clear();
}
inline const ::InterfaceInfos& GPort::interface_stats(int index) const {
  // @@protoc_insertion_point(field_get:GPort.interface_stats)
  return interface_stats_.Get(index);
}
inline ::InterfaceInfos* GPort::mutable_interface_stats(int index) {
  // @@protoc_insertion_point(field_mutable:GPort.interface_stats)
  return interface_stats_.Mutable(index);
}
inline ::InterfaceInfos* GPort::add_interface_stats() {
  // @@protoc_insertion_point(field_add:GPort.interface_stats)
  return interface_stats_.Add();
}
inline ::google::protobuf::RepeatedPtrField< ::InterfaceInfos >*
GPort::mutable_interface_stats() {
  // @@protoc_insertion_point(field_mutable_list:GPort.interface_stats)
  return &interface_stats_;
}
inline const ::google::protobuf::RepeatedPtrField< ::InterfaceInfos >&
GPort::interface_stats() const {
  // @@protoc_insertion_point(field_list:GPort.interface_stats)
  return interface_stats_;
}

// -------------------------------------------------------------------

// InterfaceInfos

// required string if_name = 1;
inline bool InterfaceInfos::has_if_name() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void InterfaceInfos::set_has_if_name() {
  _has_bits_[0] |= 0x00000001u;
}
inline void InterfaceInfos::clear_has_if_name() {
  _has_bits_[0] &= ~0x00000001u;
}
inline void InterfaceInfos::clear_if_name() {
  if_name_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  clear_has_if_name();
}
inline const ::std::string& InterfaceInfos::if_name() const {
  // @@protoc_insertion_point(field_get:InterfaceInfos.if_name)
  return if_name_.GetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline void InterfaceInfos::set_if_name(const ::std::string& value) {
  set_has_if_name();
  if_name_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set:InterfaceInfos.if_name)
}
inline void InterfaceInfos::set_if_name(const char* value) {
  set_has_if_name();
  if_name_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:InterfaceInfos.if_name)
}
inline void InterfaceInfos::set_if_name(const char* value, size_t size) {
  set_has_if_name();
  if_name_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:InterfaceInfos.if_name)
}
inline ::std::string* InterfaceInfos::mutable_if_name() {
  set_has_if_name();
  // @@protoc_insertion_point(field_mutable:InterfaceInfos.if_name)
  return if_name_.MutableNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline ::std::string* InterfaceInfos::release_if_name() {
  clear_has_if_name();
  return if_name_.ReleaseNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline void InterfaceInfos::set_allocated_if_name(::std::string* if_name) {
  if (if_name != NULL) {
    set_has_if_name();
  } else {
    clear_has_if_name();
  }
  if_name_.SetAllocatedNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), if_name);
  // @@protoc_insertion_point(field_set_allocated:InterfaceInfos.if_name)
}

// required uint64 init_time = 2;
inline bool InterfaceInfos::has_init_time() const {
  return (_has_bits_[0] & 0x00000002u) != 0;
}
inline void InterfaceInfos::set_has_init_time() {
  _has_bits_[0] |= 0x00000002u;
}
inline void InterfaceInfos::clear_has_init_time() {
  _has_bits_[0] &= ~0x00000002u;
}
inline void InterfaceInfos::clear_init_time() {
  init_time_ = GOOGLE_ULONGLONG(0);
  clear_has_init_time();
}
inline ::google::protobuf::uint64 InterfaceInfos::init_time() const {
  // @@protoc_insertion_point(field_get:InterfaceInfos.init_time)
  return init_time_;
}
inline void InterfaceInfos::set_init_time(::google::protobuf::uint64 value) {
  set_has_init_time();
  init_time_ = value;
  // @@protoc_insertion_point(field_set:InterfaceInfos.init_time)
}

// optional uint32 snmp_if_index = 3;
inline bool InterfaceInfos::has_snmp_if_index() const {
  return (_has_bits_[0] & 0x00000004u) != 0;
}
inline void InterfaceInfos::set_has_snmp_if_index() {
  _has_bits_[0] |= 0x00000004u;
}
inline void InterfaceInfos::clear_has_snmp_if_index() {
  _has_bits_[0] &= ~0x00000004u;
}
inline void InterfaceInfos::clear_snmp_if_index() {
  snmp_if_index_ = 0u;
  clear_has_snmp_if_index();
}
inline ::google::protobuf::uint32 InterfaceInfos::snmp_if_index() const {
  // @@protoc_insertion_point(field_get:InterfaceInfos.snmp_if_index)
  return snmp_if_index_;
}
inline void InterfaceInfos::set_snmp_if_index(::google::protobuf::uint32 value) {
  set_has_snmp_if_index();
  snmp_if_index_ = value;
  // @@protoc_insertion_point(field_set:InterfaceInfos.snmp_if_index)
}

// optional string parent_ae_name = 4;
inline bool InterfaceInfos::has_parent_ae_name() const {
  return (_has_bits_[0] & 0x00000008u) != 0;
}
inline void InterfaceInfos::set_has_parent_ae_name() {
  _has_bits_[0] |= 0x00000008u;
}
inline void InterfaceInfos::clear_has_parent_ae_name() {
  _has_bits_[0] &= ~0x00000008u;
}
inline void InterfaceInfos::clear_parent_ae_name() {
  parent_ae_name_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  clear_has_parent_ae_name();
}
inline const ::std::string& InterfaceInfos::parent_ae_name() const {
  // @@protoc_insertion_point(field_get:InterfaceInfos.parent_ae_name)
  return parent_ae_name_.GetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline void InterfaceInfos::set_parent_ae_name(const ::std::string& value) {
  set_has_parent_ae_name();
  parent_ae_name_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set:InterfaceInfos.parent_ae_name)
}
inline void InterfaceInfos::set_parent_ae_name(const char* value) {
  set_has_parent_ae_name();
  parent_ae_name_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:InterfaceInfos.parent_ae_name)
}
inline void InterfaceInfos::set_parent_ae_name(const char* value, size_t size) {
  set_has_parent_ae_name();
  parent_ae_name_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:InterfaceInfos.parent_ae_name)
}
inline ::std::string* InterfaceInfos::mutable_parent_ae_name() {
  set_has_parent_ae_name();
  // @@protoc_insertion_point(field_mutable:InterfaceInfos.parent_ae_name)
  return parent_ae_name_.MutableNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline ::std::string* InterfaceInfos::release_parent_ae_name() {
  clear_has_parent_ae_name();
  return parent_ae_name_.ReleaseNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline void InterfaceInfos::set_allocated_parent_ae_name(::std::string* parent_ae_name) {
  if (parent_ae_name != NULL) {
    set_has_parent_ae_name();
  } else {
    clear_has_parent_ae_name();
  }
  parent_ae_name_.SetAllocatedNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), parent_ae_name);
  // @@protoc_insertion_point(field_set_allocated:InterfaceInfos.parent_ae_name)
}

// repeated .QueueStats egress_queue_info = 5;
inline int InterfaceInfos::egress_queue_info_size() const {
  return egress_queue_info_.size();
}
inline void InterfaceInfos::clear_egress_queue_info() {
  egress_queue_info_.Clear();
}
inline const ::QueueStats& InterfaceInfos::egress_queue_info(int index) const {
  // @@protoc_insertion_point(field_get:InterfaceInfos.egress_queue_info)
  return egress_queue_info_.Get(index);
}
inline ::QueueStats* InterfaceInfos::mutable_egress_queue_info(int index) {
  // @@protoc_insertion_point(field_mutable:InterfaceInfos.egress_queue_info)
  return egress_queue_info_.Mutable(index);
}
inline ::QueueStats* InterfaceInfos::add_egress_queue_info() {
  // @@protoc_insertion_point(field_add:InterfaceInfos.egress_queue_info)
  return egress_queue_info_.Add();
}
inline ::google::protobuf::RepeatedPtrField< ::QueueStats >*
InterfaceInfos::mutable_egress_queue_info() {
  // @@protoc_insertion_point(field_mutable_list:InterfaceInfos.egress_queue_info)
  return &egress_queue_info_;
}
inline const ::google::protobuf::RepeatedPtrField< ::QueueStats >&
InterfaceInfos::egress_queue_info() const {
  // @@protoc_insertion_point(field_list:InterfaceInfos.egress_queue_info)
  return egress_queue_info_;
}

// repeated .QueueStats ingress_queue_info = 6;
inline int InterfaceInfos::ingress_queue_info_size() const {
  return ingress_queue_info_.size();
}
inline void InterfaceInfos::clear_ingress_queue_info() {
  ingress_queue_info_.Clear();
}
inline const ::QueueStats& InterfaceInfos::ingress_queue_info(int index) const {
  // @@protoc_insertion_point(field_get:InterfaceInfos.ingress_queue_info)
  return ingress_queue_info_.Get(index);
}
inline ::QueueStats* InterfaceInfos::mutable_ingress_queue_info(int index) {
  // @@protoc_insertion_point(field_mutable:InterfaceInfos.ingress_queue_info)
  return ingress_queue_info_.Mutable(index);
}
inline ::QueueStats* InterfaceInfos::add_ingress_queue_info() {
  // @@protoc_insertion_point(field_add:InterfaceInfos.ingress_queue_info)
  return ingress_queue_info_.Add();
}
inline ::google::protobuf::RepeatedPtrField< ::QueueStats >*
InterfaceInfos::mutable_ingress_queue_info() {
  // @@protoc_insertion_point(field_mutable_list:InterfaceInfos.ingress_queue_info)
  return &ingress_queue_info_;
}
inline const ::google::protobuf::RepeatedPtrField< ::QueueStats >&
InterfaceInfos::ingress_queue_info() const {
  // @@protoc_insertion_point(field_list:InterfaceInfos.ingress_queue_info)
  return ingress_queue_info_;
}

// optional .InterfaceStats ingress_stats = 7;
inline bool InterfaceInfos::has_ingress_stats() const {
  return (_has_bits_[0] & 0x00000040u) != 0;
}
inline void InterfaceInfos::set_has_ingress_stats() {
  _has_bits_[0] |= 0x00000040u;
}
inline void InterfaceInfos::clear_has_ingress_stats() {
  _has_bits_[0] &= ~0x00000040u;
}
inline void InterfaceInfos::clear_ingress_stats() {
  if (ingress_stats_ != NULL) ingress_stats_->::InterfaceStats::Clear();
  clear_has_ingress_stats();
}
inline const ::InterfaceStats& InterfaceInfos::ingress_stats() const {
  // @@protoc_insertion_point(field_get:InterfaceInfos.ingress_stats)
  return ingress_stats_ != NULL ? *ingress_stats_ : *default_instance_->ingress_stats_;
}
inline ::InterfaceStats* InterfaceInfos::mutable_ingress_stats() {
  set_has_ingress_stats();
  if (ingress_stats_ == NULL) {
    ingress_stats_ = new ::InterfaceStats;
  }
  // @@protoc_insertion_point(field_mutable:InterfaceInfos.ingress_stats)
  return ingress_stats_;
}
inline ::InterfaceStats* InterfaceInfos::release_ingress_stats() {
  clear_has_ingress_stats();
  ::InterfaceStats* temp = ingress_stats_;
  ingress_stats_ = NULL;
  return temp;
}
inline void InterfaceInfos::set_allocated_ingress_stats(::InterfaceStats* ingress_stats) {
  delete ingress_stats_;
  ingress_stats_ = ingress_stats;
  if (ingress_stats) {
    set_has_ingress_stats();
  } else {
    clear_has_ingress_stats();
  }
  // @@protoc_insertion_point(field_set_allocated:InterfaceInfos.ingress_stats)
}

// optional .InterfaceStats egress_stats = 8;
inline bool InterfaceInfos::has_egress_stats() const {
  return (_has_bits_[0] & 0x00000080u) != 0;
}
inline void InterfaceInfos::set_has_egress_stats() {
  _has_bits_[0] |= 0x00000080u;
}
inline void InterfaceInfos::clear_has_egress_stats() {
  _has_bits_[0] &= ~0x00000080u;
}
inline void InterfaceInfos::clear_egress_stats() {
  if (egress_stats_ != NULL) egress_stats_->::InterfaceStats::Clear();
  clear_has_egress_stats();
}
inline const ::InterfaceStats& InterfaceInfos::egress_stats() const {
  // @@protoc_insertion_point(field_get:InterfaceInfos.egress_stats)
  return egress_stats_ != NULL ? *egress_stats_ : *default_instance_->egress_stats_;
}
inline ::InterfaceStats* InterfaceInfos::mutable_egress_stats() {
  set_has_egress_stats();
  if (egress_stats_ == NULL) {
    egress_stats_ = new ::InterfaceStats;
  }
  // @@protoc_insertion_point(field_mutable:InterfaceInfos.egress_stats)
  return egress_stats_;
}
inline ::InterfaceStats* InterfaceInfos::release_egress_stats() {
  clear_has_egress_stats();
  ::InterfaceStats* temp = egress_stats_;
  egress_stats_ = NULL;
  return temp;
}
inline void InterfaceInfos::set_allocated_egress_stats(::InterfaceStats* egress_stats) {
  delete egress_stats_;
  egress_stats_ = egress_stats;
  if (egress_stats) {
    set_has_egress_stats();
  } else {
    clear_has_egress_stats();
  }
  // @@protoc_insertion_point(field_set_allocated:InterfaceInfos.egress_stats)
}

// optional .IngressInterfaceErrors ingress_errors = 9;
inline bool InterfaceInfos::has_ingress_errors() const {
  return (_has_bits_[0] & 0x00000100u) != 0;
}
inline void InterfaceInfos::set_has_ingress_errors() {
  _has_bits_[0] |= 0x00000100u;
}
inline void InterfaceInfos::clear_has_ingress_errors() {
  _has_bits_[0] &= ~0x00000100u;
}
inline void InterfaceInfos::clear_ingress_errors() {
  if (ingress_errors_ != NULL) ingress_errors_->::IngressInterfaceErrors::Clear();
  clear_has_ingress_errors();
}
inline const ::IngressInterfaceErrors& InterfaceInfos::ingress_errors() const {
  // @@protoc_insertion_point(field_get:InterfaceInfos.ingress_errors)
  return ingress_errors_ != NULL ? *ingress_errors_ : *default_instance_->ingress_errors_;
}
inline ::IngressInterfaceErrors* InterfaceInfos::mutable_ingress_errors() {
  set_has_ingress_errors();
  if (ingress_errors_ == NULL) {
    ingress_errors_ = new ::IngressInterfaceErrors;
  }
  // @@protoc_insertion_point(field_mutable:InterfaceInfos.ingress_errors)
  return ingress_errors_;
}
inline ::IngressInterfaceErrors* InterfaceInfos::release_ingress_errors() {
  clear_has_ingress_errors();
  ::IngressInterfaceErrors* temp = ingress_errors_;
  ingress_errors_ = NULL;
  return temp;
}
inline void InterfaceInfos::set_allocated_ingress_errors(::IngressInterfaceErrors* ingress_errors) {
  delete ingress_errors_;
  ingress_errors_ = ingress_errors;
  if (ingress_errors) {
    set_has_ingress_errors();
  } else {
    clear_has_ingress_errors();
  }
  // @@protoc_insertion_point(field_set_allocated:InterfaceInfos.ingress_errors)
}

// optional string if_administration_status = 10;
inline bool InterfaceInfos::has_if_administration_status() const {
  return (_has_bits_[0] & 0x00000200u) != 0;
}
inline void InterfaceInfos::set_has_if_administration_status() {
  _has_bits_[0] |= 0x00000200u;
}
inline void InterfaceInfos::clear_has_if_administration_status() {
  _has_bits_[0] &= ~0x00000200u;
}
inline void InterfaceInfos::clear_if_administration_status() {
  if_administration_status_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  clear_has_if_administration_status();
}
inline const ::std::string& InterfaceInfos::if_administration_status() const {
  // @@protoc_insertion_point(field_get:InterfaceInfos.if_administration_status)
  return if_administration_status_.GetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline void InterfaceInfos::set_if_administration_status(const ::std::string& value) {
  set_has_if_administration_status();
  if_administration_status_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set:InterfaceInfos.if_administration_status)
}
inline void InterfaceInfos::set_if_administration_status(const char* value) {
  set_has_if_administration_status();
  if_administration_status_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:InterfaceInfos.if_administration_status)
}
inline void InterfaceInfos::set_if_administration_status(const char* value, size_t size) {
  set_has_if_administration_status();
  if_administration_status_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:InterfaceInfos.if_administration_status)
}
inline ::std::string* InterfaceInfos::mutable_if_administration_status() {
  set_has_if_administration_status();
  // @@protoc_insertion_point(field_mutable:InterfaceInfos.if_administration_status)
  return if_administration_status_.MutableNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline ::std::string* InterfaceInfos::release_if_administration_status() {
  clear_has_if_administration_status();
  return if_administration_status_.ReleaseNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline void InterfaceInfos::set_allocated_if_administration_status(::std::string* if_administration_status) {
  if (if_administration_status != NULL) {
    set_has_if_administration_status();
  } else {
    clear_has_if_administration_status();
  }
  if_administration_status_.SetAllocatedNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), if_administration_status);
  // @@protoc_insertion_point(field_set_allocated:InterfaceInfos.if_administration_status)
}

// optional string if_operational_status = 11;
inline bool InterfaceInfos::has_if_operational_status() const {
  return (_has_bits_[0] & 0x00000400u) != 0;
}
inline void InterfaceInfos::set_has_if_operational_status() {
  _has_bits_[0] |= 0x00000400u;
}
inline void InterfaceInfos::clear_has_if_operational_status() {
  _has_bits_[0] &= ~0x00000400u;
}
inline void InterfaceInfos::clear_if_operational_status() {
  if_operational_status_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  clear_has_if_operational_status();
}
inline const ::std::string& InterfaceInfos::if_operational_status() const {
  // @@protoc_insertion_point(field_get:InterfaceInfos.if_operational_status)
  return if_operational_status_.GetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline void InterfaceInfos::set_if_operational_status(const ::std::string& value) {
  set_has_if_operational_status();
  if_operational_status_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set:InterfaceInfos.if_operational_status)
}
inline void InterfaceInfos::set_if_operational_status(const char* value) {
  set_has_if_operational_status();
  if_operational_status_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:InterfaceInfos.if_operational_status)
}
inline void InterfaceInfos::set_if_operational_status(const char* value, size_t size) {
  set_has_if_operational_status();
  if_operational_status_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:InterfaceInfos.if_operational_status)
}
inline ::std::string* InterfaceInfos::mutable_if_operational_status() {
  set_has_if_operational_status();
  // @@protoc_insertion_point(field_mutable:InterfaceInfos.if_operational_status)
  return if_operational_status_.MutableNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline ::std::string* InterfaceInfos::release_if_operational_status() {
  clear_has_if_operational_status();
  return if_operational_status_.ReleaseNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline void InterfaceInfos::set_allocated_if_operational_status(::std::string* if_operational_status) {
  if (if_operational_status != NULL) {
    set_has_if_operational_status();
  } else {
    clear_has_if_operational_status();
  }
  if_operational_status_.SetAllocatedNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), if_operational_status);
  // @@protoc_insertion_point(field_set_allocated:InterfaceInfos.if_operational_status)
}

// optional string if_description = 12;
inline bool InterfaceInfos::has_if_description() const {
  return (_has_bits_[0] & 0x00000800u) != 0;
}
inline void InterfaceInfos::set_has_if_description() {
  _has_bits_[0] |= 0x00000800u;
}
inline void InterfaceInfos::clear_has_if_description() {
  _has_bits_[0] &= ~0x00000800u;
}
inline void InterfaceInfos::clear_if_description() {
  if_description_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  clear_has_if_description();
}
inline const ::std::string& InterfaceInfos::if_description() const {
  // @@protoc_insertion_point(field_get:InterfaceInfos.if_description)
  return if_description_.GetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline void InterfaceInfos::set_if_description(const ::std::string& value) {
  set_has_if_description();
  if_description_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set:InterfaceInfos.if_description)
}
inline void InterfaceInfos::set_if_description(const char* value) {
  set_has_if_description();
  if_description_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:InterfaceInfos.if_description)
}
inline void InterfaceInfos::set_if_description(const char* value, size_t size) {
  set_has_if_description();
  if_description_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:InterfaceInfos.if_description)
}
inline ::std::string* InterfaceInfos::mutable_if_description() {
  set_has_if_description();
  // @@protoc_insertion_point(field_mutable:InterfaceInfos.if_description)
  return if_description_.MutableNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline ::std::string* InterfaceInfos::release_if_description() {
  clear_has_if_description();
  return if_description_.ReleaseNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline void InterfaceInfos::set_allocated_if_description(::std::string* if_description) {
  if (if_description != NULL) {
    set_has_if_description();
  } else {
    clear_has_if_description();
  }
  if_description_.SetAllocatedNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), if_description);
  // @@protoc_insertion_point(field_set_allocated:InterfaceInfos.if_description)
}

// optional uint64 if_transitions = 13;
inline bool InterfaceInfos::has_if_transitions() const {
  return (_has_bits_[0] & 0x00001000u) != 0;
}
inline void InterfaceInfos::set_has_if_transitions() {
  _has_bits_[0] |= 0x00001000u;
}
inline void InterfaceInfos::clear_has_if_transitions() {
  _has_bits_[0] &= ~0x00001000u;
}
inline void InterfaceInfos::clear_if_transitions() {
  if_transitions_ = GOOGLE_ULONGLONG(0);
  clear_has_if_transitions();
}
inline ::google::protobuf::uint64 InterfaceInfos::if_transitions() const {
  // @@protoc_insertion_point(field_get:InterfaceInfos.if_transitions)
  return if_transitions_;
}
inline void InterfaceInfos::set_if_transitions(::google::protobuf::uint64 value) {
  set_has_if_transitions();
  if_transitions_ = value;
  // @@protoc_insertion_point(field_set:InterfaceInfos.if_transitions)
}

// optional uint32 ifLastChange = 14;
inline bool InterfaceInfos::has_iflastchange() const {
  return (_has_bits_[0] & 0x00002000u) != 0;
}
inline void InterfaceInfos::set_has_iflastchange() {
  _has_bits_[0] |= 0x00002000u;
}
inline void InterfaceInfos::clear_has_iflastchange() {
  _has_bits_[0] &= ~0x00002000u;
}
inline void InterfaceInfos::clear_iflastchange() {
  iflastchange_ = 0u;
  clear_has_iflastchange();
}
inline ::google::protobuf::uint32 InterfaceInfos::iflastchange() const {
  // @@protoc_insertion_point(field_get:InterfaceInfos.ifLastChange)
  return iflastchange_;
}
inline void InterfaceInfos::set_iflastchange(::google::protobuf::uint32 value) {
  set_has_iflastchange();
  iflastchange_ = value;
  // @@protoc_insertion_point(field_set:InterfaceInfos.ifLastChange)
}

// optional uint32 ifHighSpeed = 15;
inline bool InterfaceInfos::has_ifhighspeed() const {
  return (_has_bits_[0] & 0x00004000u) != 0;
}
inline void InterfaceInfos::set_has_ifhighspeed() {
  _has_bits_[0] |= 0x00004000u;
}
inline void InterfaceInfos::clear_has_ifhighspeed() {
  _has_bits_[0] &= ~0x00004000u;
}
inline void InterfaceInfos::clear_ifhighspeed() {
  ifhighspeed_ = 0u;
  clear_has_ifhighspeed();
}
inline ::google::protobuf::uint32 InterfaceInfos::ifhighspeed() const {
  // @@protoc_insertion_point(field_get:InterfaceInfos.ifHighSpeed)
  return ifhighspeed_;
}
inline void InterfaceInfos::set_ifhighspeed(::google::protobuf::uint32 value) {
  set_has_ifhighspeed();
  ifhighspeed_ = value;
  // @@protoc_insertion_point(field_set:InterfaceInfos.ifHighSpeed)
}

// -------------------------------------------------------------------

// InterfaceStats

// required uint64 if_pkts = 1;
inline bool InterfaceStats::has_if_pkts() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void InterfaceStats::set_has_if_pkts() {
  _has_bits_[0] |= 0x00000001u;
}
inline void InterfaceStats::clear_has_if_pkts() {
  _has_bits_[0] &= ~0x00000001u;
}
inline void InterfaceStats::clear_if_pkts() {
  if_pkts_ = GOOGLE_ULONGLONG(0);
  clear_has_if_pkts();
}
inline ::google::protobuf::uint64 InterfaceStats::if_pkts() const {
  // @@protoc_insertion_point(field_get:InterfaceStats.if_pkts)
  return if_pkts_;
}
inline void InterfaceStats::set_if_pkts(::google::protobuf::uint64 value) {
  set_has_if_pkts();
  if_pkts_ = value;
  // @@protoc_insertion_point(field_set:InterfaceStats.if_pkts)
}

// required uint64 if_octets = 2;
inline bool InterfaceStats::has_if_octets() const {
  return (_has_bits_[0] & 0x00000002u) != 0;
}
inline void InterfaceStats::set_has_if_octets() {
  _has_bits_[0] |= 0x00000002u;
}
inline void InterfaceStats::clear_has_if_octets() {
  _has_bits_[0] &= ~0x00000002u;
}
inline void InterfaceStats::clear_if_octets() {
  if_octets_ = GOOGLE_ULONGLONG(0);
  clear_has_if_octets();
}
inline ::google::protobuf::uint64 InterfaceStats::if_octets() const {
  // @@protoc_insertion_point(field_get:InterfaceStats.if_octets)
  return if_octets_;
}
inline void InterfaceStats::set_if_octets(::google::protobuf::uint64 value) {
  set_has_if_octets();
  if_octets_ = value;
  // @@protoc_insertion_point(field_set:InterfaceStats.if_octets)
}

// required uint64 if_1sec_pkts = 3;
inline bool InterfaceStats::has_if_1sec_pkts() const {
  return (_has_bits_[0] & 0x00000004u) != 0;
}
inline void InterfaceStats::set_has_if_1sec_pkts() {
  _has_bits_[0] |= 0x00000004u;
}
inline void InterfaceStats::clear_has_if_1sec_pkts() {
  _has_bits_[0] &= ~0x00000004u;
}
inline void InterfaceStats::clear_if_1sec_pkts() {
  if_1sec_pkts_ = GOOGLE_ULONGLONG(0);
  clear_has_if_1sec_pkts();
}
inline ::google::protobuf::uint64 InterfaceStats::if_1sec_pkts() const {
  // @@protoc_insertion_point(field_get:InterfaceStats.if_1sec_pkts)
  return if_1sec_pkts_;
}
inline void InterfaceStats::set_if_1sec_pkts(::google::protobuf::uint64 value) {
  set_has_if_1sec_pkts();
  if_1sec_pkts_ = value;
  // @@protoc_insertion_point(field_set:InterfaceStats.if_1sec_pkts)
}

// required uint64 if_1sec_octets = 4;
inline bool InterfaceStats::has_if_1sec_octets() const {
  return (_has_bits_[0] & 0x00000008u) != 0;
}
inline void InterfaceStats::set_has_if_1sec_octets() {
  _has_bits_[0] |= 0x00000008u;
}
inline void InterfaceStats::clear_has_if_1sec_octets() {
  _has_bits_[0] &= ~0x00000008u;
}
inline void InterfaceStats::clear_if_1sec_octets() {
  if_1sec_octets_ = GOOGLE_ULONGLONG(0);
  clear_has_if_1sec_octets();
}
inline ::google::protobuf::uint64 InterfaceStats::if_1sec_octets() const {
  // @@protoc_insertion_point(field_get:InterfaceStats.if_1sec_octets)
  return if_1sec_octets_;
}
inline void InterfaceStats::set_if_1sec_octets(::google::protobuf::uint64 value) {
  set_has_if_1sec_octets();
  if_1sec_octets_ = value;
  // @@protoc_insertion_point(field_set:InterfaceStats.if_1sec_octets)
}

// required uint64 if_uc_pkts = 5;
inline bool InterfaceStats::has_if_uc_pkts() const {
  return (_has_bits_[0] & 0x00000010u) != 0;
}
inline void InterfaceStats::set_has_if_uc_pkts() {
  _has_bits_[0] |= 0x00000010u;
}
inline void InterfaceStats::clear_has_if_uc_pkts() {
  _has_bits_[0] &= ~0x00000010u;
}
inline void InterfaceStats::clear_if_uc_pkts() {
  if_uc_pkts_ = GOOGLE_ULONGLONG(0);
  clear_has_if_uc_pkts();
}
inline ::google::protobuf::uint64 InterfaceStats::if_uc_pkts() const {
  // @@protoc_insertion_point(field_get:InterfaceStats.if_uc_pkts)
  return if_uc_pkts_;
}
inline void InterfaceStats::set_if_uc_pkts(::google::protobuf::uint64 value) {
  set_has_if_uc_pkts();
  if_uc_pkts_ = value;
  // @@protoc_insertion_point(field_set:InterfaceStats.if_uc_pkts)
}

// required uint64 if_mc_pkts = 6;
inline bool InterfaceStats::has_if_mc_pkts() const {
  return (_has_bits_[0] & 0x00000020u) != 0;
}
inline void InterfaceStats::set_has_if_mc_pkts() {
  _has_bits_[0] |= 0x00000020u;
}
inline void InterfaceStats::clear_has_if_mc_pkts() {
  _has_bits_[0] &= ~0x00000020u;
}
inline void InterfaceStats::clear_if_mc_pkts() {
  if_mc_pkts_ = GOOGLE_ULONGLONG(0);
  clear_has_if_mc_pkts();
}
inline ::google::protobuf::uint64 InterfaceStats::if_mc_pkts() const {
  // @@protoc_insertion_point(field_get:InterfaceStats.if_mc_pkts)
  return if_mc_pkts_;
}
inline void InterfaceStats::set_if_mc_pkts(::google::protobuf::uint64 value) {
  set_has_if_mc_pkts();
  if_mc_pkts_ = value;
  // @@protoc_insertion_point(field_set:InterfaceStats.if_mc_pkts)
}

// required uint64 if_bc_pkts = 7;
inline bool InterfaceStats::has_if_bc_pkts() const {
  return (_has_bits_[0] & 0x00000040u) != 0;
}
inline void InterfaceStats::set_has_if_bc_pkts() {
  _has_bits_[0] |= 0x00000040u;
}
inline void InterfaceStats::clear_has_if_bc_pkts() {
  _has_bits_[0] &= ~0x00000040u;
}
inline void InterfaceStats::clear_if_bc_pkts() {
  if_bc_pkts_ = GOOGLE_ULONGLONG(0);
  clear_has_if_bc_pkts();
}
inline ::google::protobuf::uint64 InterfaceStats::if_bc_pkts() const {
  // @@protoc_insertion_point(field_get:InterfaceStats.if_bc_pkts)
  return if_bc_pkts_;
}
inline void InterfaceStats::set_if_bc_pkts(::google::protobuf::uint64 value) {
  set_has_if_bc_pkts();
  if_bc_pkts_ = value;
  // @@protoc_insertion_point(field_set:InterfaceStats.if_bc_pkts)
}

// optional uint64 if_error = 8;
inline bool InterfaceStats::has_if_error() const {
  return (_has_bits_[0] & 0x00000080u) != 0;
}
inline void InterfaceStats::set_has_if_error() {
  _has_bits_[0] |= 0x00000080u;
}
inline void InterfaceStats::clear_has_if_error() {
  _has_bits_[0] &= ~0x00000080u;
}
inline void InterfaceStats::clear_if_error() {
  if_error_ = GOOGLE_ULONGLONG(0);
  clear_has_if_error();
}
inline ::google::protobuf::uint64 InterfaceStats::if_error() const {
  // @@protoc_insertion_point(field_get:InterfaceStats.if_error)
  return if_error_;
}
inline void InterfaceStats::set_if_error(::google::protobuf::uint64 value) {
  set_has_if_error();
  if_error_ = value;
  // @@protoc_insertion_point(field_set:InterfaceStats.if_error)
}

// optional uint64 if_pause_pkts = 9;
inline bool InterfaceStats::has_if_pause_pkts() const {
  return (_has_bits_[0] & 0x00000100u) != 0;
}
inline void InterfaceStats::set_has_if_pause_pkts() {
  _has_bits_[0] |= 0x00000100u;
}
inline void InterfaceStats::clear_has_if_pause_pkts() {
  _has_bits_[0] &= ~0x00000100u;
}
inline void InterfaceStats::clear_if_pause_pkts() {
  if_pause_pkts_ = GOOGLE_ULONGLONG(0);
  clear_has_if_pause_pkts();
}
inline ::google::protobuf::uint64 InterfaceStats::if_pause_pkts() const {
  // @@protoc_insertion_point(field_get:InterfaceStats.if_pause_pkts)
  return if_pause_pkts_;
}
inline void InterfaceStats::set_if_pause_pkts(::google::protobuf::uint64 value) {
  set_has_if_pause_pkts();
  if_pause_pkts_ = value;
  // @@protoc_insertion_point(field_set:InterfaceStats.if_pause_pkts)
}

// -------------------------------------------------------------------

// IngressInterfaceErrors

// optional uint64 if_in_errors = 1;
inline bool IngressInterfaceErrors::has_if_in_errors() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void IngressInterfaceErrors::set_has_if_in_errors() {
  _has_bits_[0] |= 0x00000001u;
}
inline void IngressInterfaceErrors::clear_has_if_in_errors() {
  _has_bits_[0] &= ~0x00000001u;
}
inline void IngressInterfaceErrors::clear_if_in_errors() {
  if_in_errors_ = GOOGLE_ULONGLONG(0);
  clear_has_if_in_errors();
}
inline ::google::protobuf::uint64 IngressInterfaceErrors::if_in_errors() const {
  // @@protoc_insertion_point(field_get:IngressInterfaceErrors.if_in_errors)
  return if_in_errors_;
}
inline void IngressInterfaceErrors::set_if_in_errors(::google::protobuf::uint64 value) {
  set_has_if_in_errors();
  if_in_errors_ = value;
  // @@protoc_insertion_point(field_set:IngressInterfaceErrors.if_in_errors)
}

// optional uint64 if_in_qdrops = 2;
inline bool IngressInterfaceErrors::has_if_in_qdrops() const {
  return (_has_bits_[0] & 0x00000002u) != 0;
}
inline void IngressInterfaceErrors::set_has_if_in_qdrops() {
  _has_bits_[0] |= 0x00000002u;
}
inline void IngressInterfaceErrors::clear_has_if_in_qdrops() {
  _has_bits_[0] &= ~0x00000002u;
}
inline void IngressInterfaceErrors::clear_if_in_qdrops() {
  if_in_qdrops_ = GOOGLE_ULONGLONG(0);
  clear_has_if_in_qdrops();
}
inline ::google::protobuf::uint64 IngressInterfaceErrors::if_in_qdrops() const {
  // @@protoc_insertion_point(field_get:IngressInterfaceErrors.if_in_qdrops)
  return if_in_qdrops_;
}
inline void IngressInterfaceErrors::set_if_in_qdrops(::google::protobuf::uint64 value) {
  set_has_if_in_qdrops();
  if_in_qdrops_ = value;
  // @@protoc_insertion_point(field_set:IngressInterfaceErrors.if_in_qdrops)
}

// optional uint64 if_in_frame_errors = 3;
inline bool IngressInterfaceErrors::has_if_in_frame_errors() const {
  return (_has_bits_[0] & 0x00000004u) != 0;
}
inline void IngressInterfaceErrors::set_has_if_in_frame_errors() {
  _has_bits_[0] |= 0x00000004u;
}
inline void IngressInterfaceErrors::clear_has_if_in_frame_errors() {
  _has_bits_[0] &= ~0x00000004u;
}
inline void IngressInterfaceErrors::clear_if_in_frame_errors() {
  if_in_frame_errors_ = GOOGLE_ULONGLONG(0);
  clear_has_if_in_frame_errors();
}
inline ::google::protobuf::uint64 IngressInterfaceErrors::if_in_frame_errors() const {
  // @@protoc_insertion_point(field_get:IngressInterfaceErrors.if_in_frame_errors)
  return if_in_frame_errors_;
}
inline void IngressInterfaceErrors::set_if_in_frame_errors(::google::protobuf::uint64 value) {
  set_has_if_in_frame_errors();
  if_in_frame_errors_ = value;
  // @@protoc_insertion_point(field_set:IngressInterfaceErrors.if_in_frame_errors)
}

// optional uint64 if_in_discards = 4;
inline bool IngressInterfaceErrors::has_if_in_discards() const {
  return (_has_bits_[0] & 0x00000008u) != 0;
}
inline void IngressInterfaceErrors::set_has_if_in_discards() {
  _has_bits_[0] |= 0x00000008u;
}
inline void IngressInterfaceErrors::clear_has_if_in_discards() {
  _has_bits_[0] &= ~0x00000008u;
}
inline void IngressInterfaceErrors::clear_if_in_discards() {
  if_in_discards_ = GOOGLE_ULONGLONG(0);
  clear_has_if_in_discards();
}
inline ::google::protobuf::uint64 IngressInterfaceErrors::if_in_discards() const {
  // @@protoc_insertion_point(field_get:IngressInterfaceErrors.if_in_discards)
  return if_in_discards_;
}
inline void IngressInterfaceErrors::set_if_in_discards(::google::protobuf::uint64 value) {
  set_has_if_in_discards();
  if_in_discards_ = value;
  // @@protoc_insertion_point(field_set:IngressInterfaceErrors.if_in_discards)
}

// optional uint64 if_in_runts = 5;
inline bool IngressInterfaceErrors::has_if_in_runts() const {
  return (_has_bits_[0] & 0x00000010u) != 0;
}
inline void IngressInterfaceErrors::set_has_if_in_runts() {
  _has_bits_[0] |= 0x00000010u;
}
inline void IngressInterfaceErrors::clear_has_if_in_runts() {
  _has_bits_[0] &= ~0x00000010u;
}
inline void IngressInterfaceErrors::clear_if_in_runts() {
  if_in_runts_ = GOOGLE_ULONGLONG(0);
  clear_has_if_in_runts();
}
inline ::google::protobuf::uint64 IngressInterfaceErrors::if_in_runts() const {
  // @@protoc_insertion_point(field_get:IngressInterfaceErrors.if_in_runts)
  return if_in_runts_;
}
inline void IngressInterfaceErrors::set_if_in_runts(::google::protobuf::uint64 value) {
  set_has_if_in_runts();
  if_in_runts_ = value;
  // @@protoc_insertion_point(field_set:IngressInterfaceErrors.if_in_runts)
}

// optional uint64 if_in_l3_incompletes = 6;
inline bool IngressInterfaceErrors::has_if_in_l3_incompletes() const {
  return (_has_bits_[0] & 0x00000020u) != 0;
}
inline void IngressInterfaceErrors::set_has_if_in_l3_incompletes() {
  _has_bits_[0] |= 0x00000020u;
}
inline void IngressInterfaceErrors::clear_has_if_in_l3_incompletes() {
  _has_bits_[0] &= ~0x00000020u;
}
inline void IngressInterfaceErrors::clear_if_in_l3_incompletes() {
  if_in_l3_incompletes_ = GOOGLE_ULONGLONG(0);
  clear_has_if_in_l3_incompletes();
}
inline ::google::protobuf::uint64 IngressInterfaceErrors::if_in_l3_incompletes() const {
  // @@protoc_insertion_point(field_get:IngressInterfaceErrors.if_in_l3_incompletes)
  return if_in_l3_incompletes_;
}
inline void IngressInterfaceErrors::set_if_in_l3_incompletes(::google::protobuf::uint64 value) {
  set_has_if_in_l3_incompletes();
  if_in_l3_incompletes_ = value;
  // @@protoc_insertion_point(field_set:IngressInterfaceErrors.if_in_l3_incompletes)
}

// optional uint64 if_in_l2chan_errors = 7;
inline bool IngressInterfaceErrors::has_if_in_l2chan_errors() const {
  return (_has_bits_[0] & 0x00000040u) != 0;
}
inline void IngressInterfaceErrors::set_has_if_in_l2chan_errors() {
  _has_bits_[0] |= 0x00000040u;
}
inline void IngressInterfaceErrors::clear_has_if_in_l2chan_errors() {
  _has_bits_[0] &= ~0x00000040u;
}
inline void IngressInterfaceErrors::clear_if_in_l2chan_errors() {
  if_in_l2chan_errors_ = GOOGLE_ULONGLONG(0);
  clear_has_if_in_l2chan_errors();
}
inline ::google::protobuf::uint64 IngressInterfaceErrors::if_in_l2chan_errors() const {
  // @@protoc_insertion_point(field_get:IngressInterfaceErrors.if_in_l2chan_errors)
  return if_in_l2chan_errors_;
}
inline void IngressInterfaceErrors::set_if_in_l2chan_errors(::google::protobuf::uint64 value) {
  set_has_if_in_l2chan_errors();
  if_in_l2chan_errors_ = value;
  // @@protoc_insertion_point(field_set:IngressInterfaceErrors.if_in_l2chan_errors)
}

// optional uint64 if_in_l2_mismatch_timeouts = 8;
inline bool IngressInterfaceErrors::has_if_in_l2_mismatch_timeouts() const {
  return (_has_bits_[0] & 0x00000080u) != 0;
}
inline void IngressInterfaceErrors::set_has_if_in_l2_mismatch_timeouts() {
  _has_bits_[0] |= 0x00000080u;
}
inline void IngressInterfaceErrors::clear_has_if_in_l2_mismatch_timeouts() {
  _has_bits_[0] &= ~0x00000080u;
}
inline void IngressInterfaceErrors::clear_if_in_l2_mismatch_timeouts() {
  if_in_l2_mismatch_timeouts_ = GOOGLE_ULONGLONG(0);
  clear_has_if_in_l2_mismatch_timeouts();
}
inline ::google::protobuf::uint64 IngressInterfaceErrors::if_in_l2_mismatch_timeouts() const {
  // @@protoc_insertion_point(field_get:IngressInterfaceErrors.if_in_l2_mismatch_timeouts)
  return if_in_l2_mismatch_timeouts_;
}
inline void IngressInterfaceErrors::set_if_in_l2_mismatch_timeouts(::google::protobuf::uint64 value) {
  set_has_if_in_l2_mismatch_timeouts();
  if_in_l2_mismatch_timeouts_ = value;
  // @@protoc_insertion_point(field_set:IngressInterfaceErrors.if_in_l2_mismatch_timeouts)
}

// optional uint64 if_in_fifo_errors = 9;
inline bool IngressInterfaceErrors::has_if_in_fifo_errors() const {
  return (_has_bits_[0] & 0x00000100u) != 0;
}
inline void IngressInterfaceErrors::set_has_if_in_fifo_errors() {
  _has_bits_[0] |= 0x00000100u;
}
inline void IngressInterfaceErrors::clear_has_if_in_fifo_errors() {
  _has_bits_[0] &= ~0x00000100u;
}
inline void IngressInterfaceErrors::clear_if_in_fifo_errors() {
  if_in_fifo_errors_ = GOOGLE_ULONGLONG(0);
  clear_has_if_in_fifo_errors();
}
inline ::google::protobuf::uint64 IngressInterfaceErrors::if_in_fifo_errors() const {
  // @@protoc_insertion_point(field_get:IngressInterfaceErrors.if_in_fifo_errors)
  return if_in_fifo_errors_;
}
inline void IngressInterfaceErrors::set_if_in_fifo_errors(::google::protobuf::uint64 value) {
  set_has_if_in_fifo_errors();
  if_in_fifo_errors_ = value;
  // @@protoc_insertion_point(field_set:IngressInterfaceErrors.if_in_fifo_errors)
}

// optional uint64 if_in_resource_errors = 10;
inline bool IngressInterfaceErrors::has_if_in_resource_errors() const {
  return (_has_bits_[0] & 0x00000200u) != 0;
}
inline void IngressInterfaceErrors::set_has_if_in_resource_errors() {
  _has_bits_[0] |= 0x00000200u;
}
inline void IngressInterfaceErrors::clear_has_if_in_resource_errors() {
  _has_bits_[0] &= ~0x00000200u;
}
inline void IngressInterfaceErrors::clear_if_in_resource_errors() {
  if_in_resource_errors_ = GOOGLE_ULONGLONG(0);
  clear_has_if_in_resource_errors();
}
inline ::google::protobuf::uint64 IngressInterfaceErrors::if_in_resource_errors() const {
  // @@protoc_insertion_point(field_get:IngressInterfaceErrors.if_in_resource_errors)
  return if_in_resource_errors_;
}
inline void IngressInterfaceErrors::set_if_in_resource_errors(::google::protobuf::uint64 value) {
  set_has_if_in_resource_errors();
  if_in_resource_errors_ = value;
  // @@protoc_insertion_point(field_set:IngressInterfaceErrors.if_in_resource_errors)
}

// -------------------------------------------------------------------

// QueueStats

// optional uint32 queue_number = 1;
inline bool QueueStats::has_queue_number() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void QueueStats::set_has_queue_number() {
  _has_bits_[0] |= 0x00000001u;
}
inline void QueueStats::clear_has_queue_number() {
  _has_bits_[0] &= ~0x00000001u;
}
inline void QueueStats::clear_queue_number() {
  queue_number_ = 0u;
  clear_has_queue_number();
}
inline ::google::protobuf::uint32 QueueStats::queue_number() const {
  // @@protoc_insertion_point(field_get:QueueStats.queue_number)
  return queue_number_;
}
inline void QueueStats::set_queue_number(::google::protobuf::uint32 value) {
  set_has_queue_number();
  queue_number_ = value;
  // @@protoc_insertion_point(field_set:QueueStats.queue_number)
}

// optional uint64 packets = 2;
inline bool QueueStats::has_packets() const {
  return (_has_bits_[0] & 0x00000002u) != 0;
}
inline void QueueStats::set_has_packets() {
  _has_bits_[0] |= 0x00000002u;
}
inline void QueueStats::clear_has_packets() {
  _has_bits_[0] &= ~0x00000002u;
}
inline void QueueStats::clear_packets() {
  packets_ = GOOGLE_ULONGLONG(0);
  clear_has_packets();
}
inline ::google::protobuf::uint64 QueueStats::packets() const {
  // @@protoc_insertion_point(field_get:QueueStats.packets)
  return packets_;
}
inline void QueueStats::set_packets(::google::protobuf::uint64 value) {
  set_has_packets();
  packets_ = value;
  // @@protoc_insertion_point(field_set:QueueStats.packets)
}

// optional uint64 bytes = 3;
inline bool QueueStats::has_bytes() const {
  return (_has_bits_[0] & 0x00000004u) != 0;
}
inline void QueueStats::set_has_bytes() {
  _has_bits_[0] |= 0x00000004u;
}
inline void QueueStats::clear_has_bytes() {
  _has_bits_[0] &= ~0x00000004u;
}
inline void QueueStats::clear_bytes() {
  bytes_ = GOOGLE_ULONGLONG(0);
  clear_has_bytes();
}
inline ::google::protobuf::uint64 QueueStats::bytes() const {
  // @@protoc_insertion_point(field_get:QueueStats.bytes)
  return bytes_;
}
inline void QueueStats::set_bytes(::google::protobuf::uint64 value) {
  set_has_bytes();
  bytes_ = value;
  // @@protoc_insertion_point(field_set:QueueStats.bytes)
}

// optional uint64 tail_drop_packets = 4;
inline bool QueueStats::has_tail_drop_packets() const {
  return (_has_bits_[0] & 0x00000008u) != 0;
}
inline void QueueStats::set_has_tail_drop_packets() {
  _has_bits_[0] |= 0x00000008u;
}
inline void QueueStats::clear_has_tail_drop_packets() {
  _has_bits_[0] &= ~0x00000008u;
}
inline void QueueStats::clear_tail_drop_packets() {
  tail_drop_packets_ = GOOGLE_ULONGLONG(0);
  clear_has_tail_drop_packets();
}
inline ::google::protobuf::uint64 QueueStats::tail_drop_packets() const {
  // @@protoc_insertion_point(field_get:QueueStats.tail_drop_packets)
  return tail_drop_packets_;
}
inline void QueueStats::set_tail_drop_packets(::google::protobuf::uint64 value) {
  set_has_tail_drop_packets();
  tail_drop_packets_ = value;
  // @@protoc_insertion_point(field_set:QueueStats.tail_drop_packets)
}

// optional uint64 rl_drop_packets = 5;
inline bool QueueStats::has_rl_drop_packets() const {
  return (_has_bits_[0] & 0x00000010u) != 0;
}
inline void QueueStats::set_has_rl_drop_packets() {
  _has_bits_[0] |= 0x00000010u;
}
inline void QueueStats::clear_has_rl_drop_packets() {
  _has_bits_[0] &= ~0x00000010u;
}
inline void QueueStats::clear_rl_drop_packets() {
  rl_drop_packets_ = GOOGLE_ULONGLONG(0);
  clear_has_rl_drop_packets();
}
inline ::google::protobuf::uint64 QueueStats::rl_drop_packets() const {
  // @@protoc_insertion_point(field_get:QueueStats.rl_drop_packets)
  return rl_drop_packets_;
}
inline void QueueStats::set_rl_drop_packets(::google::protobuf::uint64 value) {
  set_has_rl_drop_packets();
  rl_drop_packets_ = value;
  // @@protoc_insertion_point(field_set:QueueStats.rl_drop_packets)
}

// optional uint64 rl_drop_bytes = 6;
inline bool QueueStats::has_rl_drop_bytes() const {
  return (_has_bits_[0] & 0x00000020u) != 0;
}
inline void QueueStats::set_has_rl_drop_bytes() {
  _has_bits_[0] |= 0x00000020u;
}
inline void QueueStats::clear_has_rl_drop_bytes() {
  _has_bits_[0] &= ~0x00000020u;
}
inline void QueueStats::clear_rl_drop_bytes() {
  rl_drop_bytes_ = GOOGLE_ULONGLONG(0);
  clear_has_rl_drop_bytes();
}
inline ::google::protobuf::uint64 QueueStats::rl_drop_bytes() const {
  // @@protoc_insertion_point(field_get:QueueStats.rl_drop_bytes)
  return rl_drop_bytes_;
}
inline void QueueStats::set_rl_drop_bytes(::google::protobuf::uint64 value) {
  set_has_rl_drop_bytes();
  rl_drop_bytes_ = value;
  // @@protoc_insertion_point(field_set:QueueStats.rl_drop_bytes)
}

// optional uint64 red_drop_packets = 7;
inline bool QueueStats::has_red_drop_packets() const {
  return (_has_bits_[0] & 0x00000040u) != 0;
}
inline void QueueStats::set_has_red_drop_packets() {
  _has_bits_[0] |= 0x00000040u;
}
inline void QueueStats::clear_has_red_drop_packets() {
  _has_bits_[0] &= ~0x00000040u;
}
inline void QueueStats::clear_red_drop_packets() {
  red_drop_packets_ = GOOGLE_ULONGLONG(0);
  clear_has_red_drop_packets();
}
inline ::google::protobuf::uint64 QueueStats::red_drop_packets() const {
  // @@protoc_insertion_point(field_get:QueueStats.red_drop_packets)
  return red_drop_packets_;
}
inline void QueueStats::set_red_drop_packets(::google::protobuf::uint64 value) {
  set_has_red_drop_packets();
  red_drop_packets_ = value;
  // @@protoc_insertion_point(field_set:QueueStats.red_drop_packets)
}

// optional uint64 red_drop_bytes = 8;
inline bool QueueStats::has_red_drop_bytes() const {
  return (_has_bits_[0] & 0x00000080u) != 0;
}
inline void QueueStats::set_has_red_drop_bytes() {
  _has_bits_[0] |= 0x00000080u;
}
inline void QueueStats::clear_has_red_drop_bytes() {
  _has_bits_[0] &= ~0x00000080u;
}
inline void QueueStats::clear_red_drop_bytes() {
  red_drop_bytes_ = GOOGLE_ULONGLONG(0);
  clear_has_red_drop_bytes();
}
inline ::google::protobuf::uint64 QueueStats::red_drop_bytes() const {
  // @@protoc_insertion_point(field_get:QueueStats.red_drop_bytes)
  return red_drop_bytes_;
}
inline void QueueStats::set_red_drop_bytes(::google::protobuf::uint64 value) {
  set_has_red_drop_bytes();
  red_drop_bytes_ = value;
  // @@protoc_insertion_point(field_set:QueueStats.red_drop_bytes)
}

// optional uint64 avg_buffer_occupancy = 9;
inline bool QueueStats::has_avg_buffer_occupancy() const {
  return (_has_bits_[0] & 0x00000100u) != 0;
}
inline void QueueStats::set_has_avg_buffer_occupancy() {
  _has_bits_[0] |= 0x00000100u;
}
inline void QueueStats::clear_has_avg_buffer_occupancy() {
  _has_bits_[0] &= ~0x00000100u;
}
inline void QueueStats::clear_avg_buffer_occupancy() {
  avg_buffer_occupancy_ = GOOGLE_ULONGLONG(0);
  clear_has_avg_buffer_occupancy();
}
inline ::google::protobuf::uint64 QueueStats::avg_buffer_occupancy() const {
  // @@protoc_insertion_point(field_get:QueueStats.avg_buffer_occupancy)
  return avg_buffer_occupancy_;
}
inline void QueueStats::set_avg_buffer_occupancy(::google::protobuf::uint64 value) {
  set_has_avg_buffer_occupancy();
  avg_buffer_occupancy_ = value;
  // @@protoc_insertion_point(field_set:QueueStats.avg_buffer_occupancy)
}

// optional uint64 cur_buffer_occupancy = 10;
inline bool QueueStats::has_cur_buffer_occupancy() const {
  return (_has_bits_[0] & 0x00000200u) != 0;
}
inline void QueueStats::set_has_cur_buffer_occupancy() {
  _has_bits_[0] |= 0x00000200u;
}
inline void QueueStats::clear_has_cur_buffer_occupancy() {
  _has_bits_[0] &= ~0x00000200u;
}
inline void QueueStats::clear_cur_buffer_occupancy() {
  cur_buffer_occupancy_ = GOOGLE_ULONGLONG(0);
  clear_has_cur_buffer_occupancy();
}
inline ::google::protobuf::uint64 QueueStats::cur_buffer_occupancy() const {
  // @@protoc_insertion_point(field_get:QueueStats.cur_buffer_occupancy)
  return cur_buffer_occupancy_;
}
inline void QueueStats::set_cur_buffer_occupancy(::google::protobuf::uint64 value) {
  set_has_cur_buffer_occupancy();
  cur_buffer_occupancy_ = value;
  // @@protoc_insertion_point(field_set:QueueStats.cur_buffer_occupancy)
}

// optional uint64 peak_buffer_occupancy = 11;
inline bool QueueStats::has_peak_buffer_occupancy() const {
  return (_has_bits_[0] & 0x00000400u) != 0;
}
inline void QueueStats::set_has_peak_buffer_occupancy() {
  _has_bits_[0] |= 0x00000400u;
}
inline void QueueStats::clear_has_peak_buffer_occupancy() {
  _has_bits_[0] &= ~0x00000400u;
}
inline void QueueStats::clear_peak_buffer_occupancy() {
  peak_buffer_occupancy_ = GOOGLE_ULONGLONG(0);
  clear_has_peak_buffer_occupancy();
}
inline ::google::protobuf::uint64 QueueStats::peak_buffer_occupancy() const {
  // @@protoc_insertion_point(field_get:QueueStats.peak_buffer_occupancy)
  return peak_buffer_occupancy_;
}
inline void QueueStats::set_peak_buffer_occupancy(::google::protobuf::uint64 value) {
  set_has_peak_buffer_occupancy();
  peak_buffer_occupancy_ = value;
  // @@protoc_insertion_point(field_set:QueueStats.peak_buffer_occupancy)
}

// optional uint64 allocated_buffer_size = 12;
inline bool QueueStats::has_allocated_buffer_size() const {
  return (_has_bits_[0] & 0x00000800u) != 0;
}
inline void QueueStats::set_has_allocated_buffer_size() {
  _has_bits_[0] |= 0x00000800u;
}
inline void QueueStats::clear_has_allocated_buffer_size() {
  _has_bits_[0] &= ~0x00000800u;
}
inline void QueueStats::clear_allocated_buffer_size() {
  allocated_buffer_size_ = GOOGLE_ULONGLONG(0);
  clear_has_allocated_buffer_size();
}
inline ::google::protobuf::uint64 QueueStats::allocated_buffer_size() const {
  // @@protoc_insertion_point(field_get:QueueStats.allocated_buffer_size)
  return allocated_buffer_size_;
}
inline void QueueStats::set_allocated_buffer_size(::google::protobuf::uint64 value) {
  set_has_allocated_buffer_size();
  allocated_buffer_size_ = value;
  // @@protoc_insertion_point(field_set:QueueStats.allocated_buffer_size)
}

#endif  // !PROTOBUF_INLINE_NOT_IN_HEADERS
// -------------------------------------------------------------------

// -------------------------------------------------------------------

// -------------------------------------------------------------------

// -------------------------------------------------------------------


// @@protoc_insertion_point(namespace_scope)

// @@protoc_insertion_point(global_scope)

#endif  // PROTOBUF_port_2eproto__INCLUDED
